project_id = "ihhetvwuhqohbfgkqoxw"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
port = 54327
image_transformation = { enabled = true }

[auth]
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[functions.gmail-oauth]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-enrollment-email]
verify_jwt = false

[functions.admin-enrollment-access]
verify_jwt = false

[functions.delete-message-public]
verify_jwt = false

[functions.fix-payment-status]
verify_jwt = false

[functions.save-analytics-report]
verify_jwt = false

[functions.track-analytics]
verify_jwt = false

[functions.ai-lead-scoring]
verify_jwt = false

[functions.ai-lead-scoring-job]
verify_jwt = false

[functions.analyze-smart-test]
verify_jwt = false
